CREATE DATABASE IF NOT EXISTS hiscore_db  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS recipe_db   CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS ge_db       CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS calc_db     CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS chat_db     CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON hiscore_db.* TO 'rs3'@'%';
GRANT ALL PRIVILEGES ON recipe_db.*  TO 'rs3'@'%';
GRANT ALL PRIVILEGES ON ge_db.*      TO 'rs3'@'%';
GRANT ALL PRIVILEGES ON calc_db.*    TO 'rs3'@'%';
GRANT ALL PRIVILEGES ON chat_db.*    TO 'rs3'@'%';
FLUSH PRIVILEGES;
