#!/usr/bin/env python3
"""Derive the per-service OpenAPI specs from openapi/combined.yaml.

combined.yaml is the single source of truth for the API. Each service
also serves its own spec on /swagger for debugging that service in
isolation, and those copies were previously maintained by hand — which
is how they drifted out of sync with the code and with each other.

Run `make openapi` after changing combined.yaml.
"""

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
COMBINED = ROOT / "openapi" / "combined.yaml"

# Path prefix -> owning service. Longest prefix wins, so /health/all is
# matched before /health.
OWNERS = {
    "/recipes": "recipe-service",
    "/search": "recipe-service",
    "/items": "recipe-service",
    "/prices": "ge-price-service",
    "/calc": "calc-service",
    "/hiscore": "hiscore-service",
    "/auth": "realtime-service",
    "/chat": "realtime-service",
    "/ws": "realtime-service",
    "/health/all": "gateway",
}

SERVICES = [
    "gateway",
    "hiscore-service",
    "recipe-service",
    "ge-price-service",
    "calc-service",
    "realtime-service",
]

HTTP_METHODS = {"get", "post", "put", "patch", "delete", "options", "head"}


def owner_of(path: str) -> str:
    best = ""
    for prefix in OWNERS:
        if (path == prefix or path.startswith(prefix + "/")) and len(prefix) > len(best):
            best = prefix
    return OWNERS.get(best, "gateway")


def collect_refs(node, out):
    """Gather every local $ref target name under components."""
    if isinstance(node, dict):
        for key, value in node.items():
            if key == "$ref" and isinstance(value, str) and value.startswith("#/components/"):
                out.add(value[len("#/components/"):])
            else:
                collect_refs(value, out)
    elif isinstance(node, list):
        for value in node:
            collect_refs(value, out)


def resolve(doc, pointer: str):
    """Resolve a pointer relative to #/components, e.g. "schemas/Error"."""
    cur = doc["components"]
    for part in pointer.split("/"):
        cur = cur[part]
    return cur


def closure(doc, seeds):
    """Transitively expand refs so a kept schema keeps what it needs."""
    seen, pending = set(), set(seeds)
    while pending:
        item = pending.pop()
        if item in seen:
            continue
        seen.add(item)
        nested = set()
        collect_refs(resolve(doc, item), nested)
        pending |= nested - seen
    return seen


def build(doc, service):
    paths = {
        path: item
        for path, item in doc["paths"].items()
        if owner_of(path) == service or path == "/health"
    }
    if not paths:
        return None

    refs = set()
    collect_refs(paths, refs)
    kept = closure(doc, refs)

    components = {}
    for pointer in sorted(kept):
        section, name = pointer.split("/", 1)
        components.setdefault(section, {})[name] = resolve(doc, pointer)

    info = dict(doc["info"])
    info["title"] = f"RS3 Market — {service}"
    info["description"] = (
        f"Endpoints served by **{service}**, extracted from the combined "
        "specification.\n\n"
        "This copy exists for debugging one service in isolation. Generate "
        "clients from `openapi/combined.yaml`, which describes the whole "
        "gateway surface.\n\n"
        "Generated by `scripts/split_openapi.py` — do not edit by hand."
    )

    out = {
        "openapi": doc["openapi"],
        "info": info,
        "servers": [{"url": "/", "description": service}],
        "security": [],
        "paths": paths,
    }
    tags = sorted({t for item in paths.values()
                   for op in item.values() if isinstance(op, dict)
                   for t in op.get("tags", [])})
    if tags:
        by_name = {t["name"]: t for t in doc.get("tags", [])}
        out["tags"] = [by_name.get(t, {"name": t}) for t in tags]
    if components:
        out["components"] = components
    return out


def main():
    doc = yaml.safe_load(COMBINED.read_text())
    written = []
    for service in SERVICES:
        spec = build(doc, service)
        if spec is None:
            print(f"warning: no paths for {service}", file=sys.stderr)
            continue
        target = ROOT / "openapi" / f"{service}.yaml"
        target.write_text(
            "# Generated by scripts/split_openapi.py — do not edit.\n"
            "# Source: openapi/combined.yaml\n"
            + yaml.safe_dump(spec, sort_keys=False, width=100, allow_unicode=True)
        )
        written.append(f"{target.name} ({len(spec['paths'])} paths)")
    for line in written:
        print("wrote", line)


if __name__ == "__main__":
    main()
