/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gateway liveness */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness of every upstream service */
        get: operations["getUpstreamHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recipes
         * @description Returns full recipes including their inputs. Unpaginated — use
         *     `/search/recipes` for anything user-facing.
         */
        get: operations["listRecipes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Output item IDs for matching recipes
         * @description Distinct output item IDs, filtered by skill and level range.
         *     Recipes whose output item ID is still unresolved are excluded,
         *     so every ID returned here can be priced.
         */
        get: operations["listRecipeOutputItemIds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{itemID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recipe tree for an item
         * @description Resolves every intermediate recipe needed to produce the item.
         *     Identical to `/recipes/{itemID}/tree`.
         */
        get: operations["getRecipeTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{itemID}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recipe tree for an item */
        get: operations["getRecipeTreeExplicit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search recipes by name
         * @description Paginated recipe summaries. Inputs are **not** included — fetch
         *     `/recipes/{itemID}` for the full tree.
         */
        get: operations["searchRecipes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search items by name
         * @description Searches every item that appears as a recipe output or a recipe
         *     input. `sources` says which side each item was found on.
         */
        get: operations["searchItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Grand Exchange 4-hour buy limits
         * @description Items with no known limit are **omitted** from the map rather
         *     than returned as zero, so "unknown" is distinguishable from
         *     "limited to nothing".
         */
        get: operations["getBuyLimits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest price snapshot per item */
        get: operations["getLatestPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices/history/{itemID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Price history for one item */
        get: operations["getPriceHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices/change/{itemID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Price movement over a window
         * @description Check `has_baseline` before trusting `change_pct`: `false` means
         *     we have no history reaching back that far, which is a different
         *     statement from "the price did not move".
         */
        get: operations["getPriceChange"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices/stats/{itemID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tradeability and liquidity signals
         * @description Whether an item can actually be traded at size, derived from
         *     stored snapshots plus its buy limit.
         *
         *     A margin alone is not a trading signal: a large margin on an item
         *     that trades twice a day looks identical, in a plain profit
         *     listing, to the same margin on one that moves millions of units.
         *     Sort or filter by `score` and `tier` to tell them apart, and read
         *     `observations` to see how much data the score is built on.
         */
        get: operations["getPriceStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calc/{itemID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profitability of every way to produce an item
         * @description Walks the recipe tree and evaluates each combination of buying
         *     versus crafting each input, returning one `CalcPath` per
         *     strategy, best first.
         *
         *     Ranking puts paths the player can actually perform first (when
         *     `player` is supplied), then complete paths, then by the
         *     throughput-limited GP/h where a buy limit is known.
         */
        get: operations["calculateItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calc/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profitability for several items at once
         * @description Errors are reported per entry, so one unpriceable item does not
         *     fail the request.
         */
        get: operations["calculateBatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calc/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The catalogue ranked by one headline metric
         * @description Walks every priceable recipe — around 5800 of them — and returns
         *     the best path for each, ranked by `metric`. Answers from cache
         *     on anything but the first call for a given parameter set.
         *
         *     `metric` is required; there is no default, because asking for a
         *     ranking without saying of what is a mistake worth reporting
         *     rather than guessing at.
         *
         *     `gp_per_hour` ranks on `gp_per_hour_limited`, the buy-limit-bound
         *     rate, not the raw `gp_per_hour`. The raw figure multiplies one
         *     craft's profit by a full hour of actions, which floats items
         *     nobody can produce at that rate — a godsword nobody forges six
         *     hundred times an hour — above the things people actually craft.
         *
         *     When `player` is supplied, recipes that player's levels cannot
         *     perform are dropped from the ranking entirely. A leaderboard is
         *     read as a list of things to go and do, and the highest-XP
         *     recipes in the game are end-game chains a mid-level account will
         *     never reach; they are also the ones whose rate falls back to the
         *     house default, because the level gate that refuses them refuses
         *     to derive a tick cost as well. Left in, they crowd out the
         *     reachable items with a server-invented number. Every row
         *     returned therefore has `meets_requirements: true`.
         *
         *     Without a `player` there is nothing to compare levels against,
         *     so the whole catalogue ranks and `meets_requirements` is absent.
         *
         *     An item whose calculation fails (no priceable path, upstream
         *     error) is simply absent from the ranking rather than failing the
         *     whole request, the same reasoning `/calc/batch` uses to report
         *     failures per entry.
         */
        get: operations["calculateTop"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hiscore/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Skill levels for a player
         * @description Served from cache when fresh. If the upstream is unreachable but
         *     we hold a stale copy, the stale copy is returned — check
         *     `fetched_at`.
         */
        get: operations["getPlayerHiscore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a chat account */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for a JWT
         * @description The token authenticates the WebSocket at `/ws`, where it is
         *     passed as the `token` query parameter.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent chat messages */
        get: operations["getChatHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Realtime price and chat socket
         * @description Upgrades to a WebSocket. Not usable through a generated HTTP
         *     client — connect with the browser's `WebSocket` API. It is
         *     documented here so the message payloads are generated as types.
         *
         *     Send `WsCommand` frames; receive `WsEnvelope` frames whose
         *     `payload` shape is determined by `type`:
         *
         *     | `type`      | `payload`        |
         *     |-------------|------------------|
         *     | `price`     | `PriceSnapshot`  |
         *     | `chat`      | `ChatMessage`    |
         *     | `heartbeat` | `WsHeartbeat`    |
         *     | `error`     | `WsError`        |
         *
         *     Price frames arrive only for items subscribed to on this
         *     connection; chat and heartbeat frames go to every client.
         */
        get: operations["openWebSocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Human-readable failure reason. */
            error: string;
        };
        HealthStatus: {
            /** @example ok */
            status: string;
            service?: string;
        };
        UpstreamHealth: {
            target: string;
            ok: boolean;
            status?: number;
            error?: string;
            /**
             * Format: int64
             * @description Round-trip time of the probe.
             */
            ms: number;
        };
        GatewayHealth: {
            gateway: string;
            all_upstreams_ok: boolean;
            upstreams: components["schemas"]["UpstreamHealth"][];
        };
        /**
         * @default normal
         * @enum {string}
         */
        HiscoreMode: "normal" | "ironman" | "hardcore";
        /**
         * @description Which side of a recipe an item appears on.
         * @default all
         * @enum {string}
         */
        ItemSource: "all" | "output" | "input";
        /**
         * @description Where a recipe's actions-per-hour came from. `default` means it
         *     is a house assumption, not a measured rate — the wiki rarely
         *     publishes one. Treat `default` figures as good for ranking
         *     recipes against each other, not as literal throughput. `ticks`,
         *     `ticks_level` and `ticks_forge` are derived from the wiki's tick
         *     cost and Smithing mechanics rather than assumed; `ticks_level`
         *     and `ticks_forge` additionally require a `player`, since they
         *     depend on skill levels.
         * @enum {string}
         */
        AphSource: "wiki" | "default" | "override" | "ticks" | "ticks_level" | "ticks_forge";
        PlayerSkill: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            player_id: number;
            /** @example Crafting */
            skill: string;
            level: number;
            /** Format: int64 */
            xp: number;
            /** Format: int64 */
            rank: number;
        };
        Player: {
            /** Format: int64 */
            id: number;
            name: string;
            mode: components["schemas"]["HiscoreMode"];
            /**
             * Format: date-time
             * @description When the hiscores were last read. May be old if the upstream
             *     was unreachable and a cached copy was served.
             */
            fetched_at: string;
            skills: components["schemas"]["PlayerSkill"][];
        };
        RecipeInput: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            recipe_id: number;
            /**
             * Format: int64
             * @description Grand Exchange item ID, or `0` when it could not be
             *     resolved. A zero here means the input cannot be priced, and
             *     any path depending on it is reported as incomplete.
             */
            item_id: number;
            item_name: string;
            /** @description Units consumed per craft. */
            quantity: number;
            /** @description True when this input is itself craftable. */
            is_intermediate: boolean;
        };
        Recipe: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int64 */
            output_item_id: number;
            output_item_name: string;
            /** @description Units produced per craft. */
            output_qty: number;
            skill: string;
            level_req: number;
            /** Format: double */
            xp_per_action: number;
            actions_per_hour: number;
            aph_source: components["schemas"]["AphSource"];
            /** @description Per-action tick cost from the wiki infobox. Zero when the wiki published none, or published `varies`. */
            ticks: number;
            /** @description Where the recipe is made, such as `Furnace` or `Anvil` — what separates smelting from forging within Smithing. */
            facility?: string;
            members: boolean;
            /** @example runescape.wiki */
            source: string;
            /** @description Omitted in summary listings such as `/search/recipes`. */
            inputs?: components["schemas"]["RecipeInput"][];
        };
        RecipeTreeNode: {
            recipe: components["schemas"]["Recipe"];
            /** @description Inputs that are themselves craftable. */
            children?: components["schemas"]["RecipeTreeNode"][] | null;
            depth: number;
        };
        RecipeTree: {
            root: components["schemas"]["RecipeTreeNode"];
        };
        RecipeListResponse: {
            count: number;
            recipes: components["schemas"]["Recipe"][];
        };
        RecipeIdsResponse: {
            skill: string;
            min_level: number;
            max_level: number;
            count: number;
            item_ids: number[];
        };
        RecipeSearchResponse: {
            query: string;
            /** @description Rows on this page. */
            count: number;
            /**
             * Format: int64
             * @description Rows matching across all pages.
             */
            total: number;
            limit: number;
            offset: number;
            recipes: components["schemas"]["Recipe"][];
        };
        ItemSummary: {
            /** Format: int64 */
            item_id: number;
            name: string;
            /** @description Which sides of a recipe this item was found on. */
            sources: ("input" | "output")[];
        };
        ItemSearchResponse: {
            query: string;
            source: components["schemas"]["ItemSource"];
            count: number;
            /** Format: int64 */
            total: number;
            limit: number;
            offset: number;
            items: components["schemas"]["ItemSummary"][];
        };
        BuyLimitsResponse: {
            count: number;
            /**
             * @description Item ID (as a string key) to its 4-hour buy limit. Items
             *     with no known limit are absent.
             * @example {
             *       "1513": 25000,
             *       "2363": 10000
             *     }
             */
            limits: {
                [key: string]: number;
            };
        };
        PriceSnapshot: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            item_id: number;
            /**
             * Format: date-time
             * @description When this observation was recorded.
             */
            ts: string;
            /**
             * Format: int64
             * @description The Grand Exchange **guide price** in GP. This is the only
             *     price RS3 publishes — it is not an instant-buy or
             *     instant-sell quote, and there is no bid/ask spread in this
             *     data. Apply an explicit spread assumption before treating it
             *     as a price you could transact at.
             */
            price: number;
            /**
             * Format: int64
             * @description Units traded as reported by the exchange. Zero is common and
             *     may mean "not reported" rather than "nothing traded" — see
             *     `LiquidityStats` for a more robust signal.
             */
            volume: number;
        };
        LatestPricesResponse: {
            count: number;
            /** @description Items never polled are absent rather than zeroed. */
            prices: components["schemas"]["PriceSnapshot"][];
        };
        PriceHistoryResponse: {
            /** Format: int64 */
            item_id: number;
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            count: number;
            /** @description Ascending by timestamp. */
            history: components["schemas"]["PriceSnapshot"][];
        };
        PriceChange: {
            /** Format: int64 */
            item_id: number;
            /** Format: double */
            window_hours: number;
            /** Format: double */
            change_pct: number;
            /** Format: int64 */
            change_gp: number;
            /** @description Null when the item has never been polled. */
            current?: components["schemas"]["PriceSnapshot"] | null;
            /** @description Null when history does not reach back that far. */
            previous?: components["schemas"]["PriceSnapshot"] | null;
            /**
             * @description False means there was no snapshot old enough to compare
             *     against, so `change_pct` is zero for lack of data — not
             *     because the price held steady.
             */
            has_baseline: boolean;
        };
        /**
         * @description Coarse bucket of `score`, for filtering.
         * @enum {string}
         */
        LiquidityTier: "high" | "medium" | "low" | "unknown";
        LiquidityStats: {
            /** Format: int64 */
            item_id: number;
            /**
             * @description Snapshots in the window. A score built on one or two samples
             *     is not worth much — show this next to the score.
             */
            observations: number;
            distinct_prices: number;
            /** Format: int64 */
            price_min: number;
            /** Format: int64 */
            price_max: number;
            /** Format: double */
            price_avg: number;
            /** Format: int64 */
            price_last: number;
            /**
             * Format: double
             * @description Peak-to-trough swing as a percentage of the mean.
             */
            volatility_pct: number;
            /** Format: double */
            volume_avg: number;
            /** Format: int64 */
            volume_last: number;
            /**
             * Format: date-time
             * @description When the price last actually moved — not when it was last
             *     polled. Null if it never moved within the window.
             */
            last_change_at?: string | null;
            /** Format: double */
            stale_for_hours: number;
            /**
             * @description Blend of traded volume (60%), how recently the price moved
             *     (25%) and how often it moves (15%). A ranking aid, not a
             *     probability.
             */
            score: number;
            tier: components["schemas"]["LiquidityTier"];
            /** @description 4-hour Grand Exchange buy limit; `0` when unknown. */
            buy_limit_4h: number;
        };
        CalcAssumptions: {
            /**
             * @description What the underlying price numbers actually are.
             * @enum {string}
             */
            price_basis: "ge_guide_price";
            /**
             * Format: double
             * @description Assumed round-trip buy/sell gap. Buys modelled at
             *     `price * (1 + spread/200)`, sells at `price * (1 - spread/200)`.
             */
            spread_pct: number;
            /** Format: double */
            tax_pct: number;
            /** Format: int64 */
            tax_cap_per_item: number;
            /** Format: int64 */
            tax_exempt_below: number;
            player?: string;
            mode?: components["schemas"]["HiscoreMode"];
            /**
             * @description Inventory slots assumed available before a bank trip is
             *     needed, feeding every actions-per-hour figure derived from
             *     ticks (`aph_source` of `ticks`, `ticks_level` or
             *     `ticks_forge`).
             */
            inventory_slots: number;
            /** @description Ticks charged for a bank trip when the inventory runs out. */
            bank_trip_ticks: number;
            /**
             * @description The `boosts` query parameter, echoed back verbatim. Absent
             *     when no boosts were declared.
             */
            boosts?: string;
        };
        /**
         * @description The ceiling the Grand Exchange buy limits put on a strategy,
         *     regardless of how fast you can click. Usually far below
         *     `gp_per_hour`.
         */
        CalcThroughput: {
            /** Format: int64 */
            binding_item_id: number;
            /** @description The bought input whose buy limit binds hardest. */
            binding_item_name: string;
            binding_limit_4h: number;
            max_crafts_per_4h: number;
            /**
             * Format: double
             * @description The lower of the buy-limit rate and the rate the whole path
             *     completes at (`1 / total_hours`). Not the root step's
             *     `actions_per_hour`: on a chained path the root step runs
             *     several times for each finished item.
             */
            crafts_per_hour: number;
            /**
             * Format: double
             * @description Profit per craft at the limit-constrained rate.
             */
            gp_per_hour: number;
        };
        SkillRequirement: {
            skill: string;
            required: number;
            /** @description The player's level; `0` if they lack the skill. */
            actual: number;
            met: boolean;
        };
        CalcStep: {
            recipe: string;
            skill: string;
            level_req: number;
            /** Format: double */
            xp: number;
            /**
             * Format: double
             * @description Fractional: an item costing 80 bars takes about 1.7
             *     hours, so its honest rate is well below one an hour.
             */
            aph: number;
            aph_source: components["schemas"]["AphSource"];
            /** @description Times this step runs per unit of the final output. */
            runs: number;
            /** Format: double */
            buy_cost: number;
            /** Format: double */
            sell_revenue: number;
            /** Format: double */
            profit: number;
        };
        /** @description One strategy for producing the item. */
        CalcPath: {
            /** @description Recipe names in execution order. */
            path: string[];
            steps: components["schemas"]["CalcStep"][];
            /**
             * Format: double
             * @description Net GP per craft of the final output, after tax.
             */
            profit_per_craft: number;
            /**
             * Format: double
             * @description Unconstrained rate. Prefer `throughput.gp_per_hour` when
             *     present — this figure ignores buy limits.
             */
            gp_per_hour: number;
            /** Format: double */
            xp_per_hour: number;
            /** Format: double */
            gp_per_xp: number;
            /** Format: double */
            roi_pct: number;
            /** Format: double */
            total_hours: number;
            /** Format: double */
            total_xp: number;
            /** Format: double */
            buy_cost: number;
            /** Format: double */
            sell_revenue: number;
            /** Format: double */
            tax_paid: number;
            /**
             * Format: double
             * @description Fractional: an item costing 80 bars takes about 1.7
             *     hours, so its honest rate is well below one an hour.
             */
            actions_per_hour: number;
            aph_source: components["schemas"]["AphSource"];
            /**
             * @description False means an input had no price and was costed at zero, so
             *     every money figure here is an upper bound. Only ever false
             *     when `include_incomplete=true` was passed.
             */
            complete: boolean;
            /** @description Names of inputs that could not be priced. */
            unpriced_inputs?: string[];
            /** @description Null when no bought input has a known buy limit. */
            throughput?: components["schemas"]["CalcThroughput"] | null;
            /** @description Null unless a `player` was supplied. */
            meets_requirements?: boolean | null;
            /** @description Present only when a `player` was supplied. */
            skill_requirements?: components["schemas"]["SkillRequirement"][];
        };
        CalcResult: {
            /** Format: int64 */
            item_id: number;
            /** Format: date-time */
            generated_at: string;
            assumptions: components["schemas"]["CalcAssumptions"];
            /** @description Best first. */
            paths: components["schemas"]["CalcPath"][];
            cached: boolean;
        };
        CalcBatchEntry: {
            /** Format: int64 */
            item_id: number;
            result?: components["schemas"]["CalcResult"] | null;
            /** @description Set instead of `result` when this item failed. */
            error?: string;
        };
        CalcBatchResponse: {
            count: number;
            results: components["schemas"]["CalcBatchEntry"][];
        };
        /**
         * @description What /calc/top ranks by. No default — it is required.
         * @enum {string}
         */
        TopMetric: "xp_per_hour" | "gp_per_hour" | "gp_per_xp";
        /** @description The best production path for one item, under one metric. */
        TopRow: {
            /** Format: int64 */
            item_id: number;
            name: string;
            skill: string;
            level_req: number;
            /** Format: double */
            xp_per_hour: number;
            /**
             * Format: double
             * @description Unconstrained rate. `gp_per_hour` ranks on
             *     `gp_per_hour_limited` instead — prefer that field.
             */
            gp_per_hour: number;
            /**
             * Format: double
             * @description `gp_per_hour` capped by the binding input's Grand Exchange
             *     buy limit where one is known, equal to `gp_per_hour`
             *     otherwise. Never above `gp_per_hour`: the cap is on how
             *     often the whole path can be completed. This is the field
             *     `metric=gp_per_hour` sorts on.
             */
            gp_per_hour_limited: number;
            /** Format: double */
            gp_per_xp: number;
            /**
             * Format: double
             * @description Fractional: an item costing 80 bars takes about 1.7
             *     hours, so its honest rate is well below one an hour.
             */
            actions_per_hour: number;
            aph_source: components["schemas"]["AphSource"];
            /**
             * @description False means an input had no price and was costed at zero.
             *     Only ever false when `include_incomplete=true` was passed.
             */
            complete: boolean;
            /**
             * @description The bought input whose buy limit produced
             *     `gp_per_hour_limited`. Absent when no bought input has a
             *     known buy limit.
             */
            binding_item_name?: string;
            /**
             * @description Whether the player has every level this path needs. Always
             *     `true` on a ranking, which drops what the player cannot
             *     perform; absent when no `player` was supplied, since with no
             *     hiscore data "you qualify" would be a guess presented as
             *     fact.
             */
            meets_requirements?: boolean;
        };
        TopResponse: {
            metric: components["schemas"]["TopMetric"];
            /** @description Number of rows returned (at most `limit`). */
            count: number;
            /**
             * @description Ordered by `metric`, best first, with two qualifications
             *     ahead of it: an incomplete row (an input had no price, so
             *     its money figures are upper bounds) sorts below a complete
             *     one, and `item_id` ascending breaks an exact tie so two
             *     identical requests return the same rows at the `limit`
             *     boundary. With a `player`, only recipes that player can
             *     actually perform appear here at all.
             */
            rows: components["schemas"]["TopRow"][];
            assumptions: components["schemas"]["CalcAssumptions"];
        };
        Credentials: {
            username: string;
            /** Format: password */
            password: string;
        };
        RegisteredUser: {
            /** Format: int64 */
            id: number;
            username: string;
        };
        LoginResponse: {
            /** @description JWT; pass as `?token=` when opening `/ws`. */
            token: string;
        };
        ChatMessage: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            user_id: number;
            username: string;
            body: string;
            /** Format: date-time */
            created_at: string;
        };
        ChatHistoryResponse: {
            messages: components["schemas"]["ChatMessage"][];
        };
        /** @enum {string} */
        WsCommandAction: "subscribe" | "unsubscribe" | "chat";
        /** @description A frame sent from the client to the server. */
        WsCommand: {
            action: components["schemas"]["WsCommandAction"];
            /** @description Required for `subscribe` and `unsubscribe`. */
            item_ids?: number[];
            /** @description Required for `chat`. */
            body?: string;
        };
        /** @enum {string} */
        WsEnvelopeType: "price" | "chat" | "heartbeat" | "error";
        /**
         * @description A frame sent from the server to the client. `type` determines
         *     how to parse `payload`.
         */
        WsEnvelope: {
            type: components["schemas"]["WsEnvelopeType"];
            /**
             * @description `PriceSnapshot` for `price`, `ChatMessage` for `chat`,
             *     `WsHeartbeat` for `heartbeat`, `WsError` for `error`.
             */
            payload?: components["schemas"]["PriceSnapshot"] | components["schemas"]["ChatMessage"] | components["schemas"]["WsHeartbeat"] | components["schemas"]["WsError"];
        };
        WsHeartbeat: {
            /** Format: date-time */
            ts: string;
        };
        WsError: {
            message: string;
        };
    };
    responses: {
        /** @description The request was malformed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Grand Exchange item ID.
         * @example 1513
         */
        ItemIdPath: number;
        /**
         * @description Comma-separated Grand Exchange item IDs (max 500).
         * @example 1513,1515,2363
         */
        ItemIdsQuery: string;
        /**
         * @description Lookback as a Go duration (`24h`, `168h`) or a plain number of
         *     hours (`24`).
         * @example 24h
         */
        Window: string;
        /** @description Hiscore table to read. */
        HiscoreMode: components["schemas"]["HiscoreMode"];
        /**
         * @description Comma-separated forging boosts to assume when simulating a
         *     Smithing anvil recipe (`aph_source: ticks_forge`). Ignored by
         *     every other recipe. Unknown tokens are rejected with a 400
         *     rather than silently ignored. Recognised tokens: `smithing_cape`,
         *     `careless5`, `luminite`, `rapid4`, `tinker2`, `juju`, `varrock4`,
         *     `crystal_hammer`, `equipment20` (raises `rapid4` and `tinker2` to
         *     their equipment-level-20 values). Omit for the conservative
         *     floor — no perk or potion assumed.
         * @example smithing_cape,rapid4,equipment20
         */
        CalcBoosts: string;
        /** @description Page size. Capped at 500. */
        Limit: number;
        /** @description Rows to skip. */
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gateway is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getUpstreamHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All upstreams healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayHealth"];
                };
            };
            /** @description At least one upstream is unhealthy. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayHealth"];
                };
            };
        };
    };
    listRecipes: {
        parameters: {
            query?: {
                /** @description Exact skill name, e.g. `Crafting`. */
                skill?: string;
                /** @description Upper bound on the recipe's level requirement. */
                level?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching recipes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeListResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listRecipeOutputItemIds: {
        parameters: {
            query?: {
                skill?: string;
                /** @description Inclusive lower bound on the level requirement. */
                min_level?: number;
                /** @description Inclusive upper bound on the level requirement. */
                level?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching output item IDs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeIdsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getRecipeTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Grand Exchange item ID.
                 * @example 1513
                 */
                itemID: components["parameters"]["ItemIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The recipe tree. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeTree"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getRecipeTreeExplicit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Grand Exchange item ID.
                 * @example 1513
                 */
                itemID: components["parameters"]["ItemIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The recipe tree. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeTree"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    searchRecipes: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring of the recipe or output name. */
                q?: string;
                skill?: string;
                min_level?: number;
                level?: number;
                /** @description Page size. Capped at 500. */
                limit?: components["parameters"]["Limit"];
                /** @description Rows to skip. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching recipes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSearchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    searchItems: {
        parameters: {
            query?: {
                q?: string;
                source?: components["schemas"]["ItemSource"];
                /** @description Page size. Capped at 500. */
                limit?: components["parameters"]["Limit"];
                /** @description Rows to skip. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemSearchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getBuyLimits: {
        parameters: {
            query: {
                /**
                 * @description Comma-separated Grand Exchange item IDs (max 500).
                 * @example 1513,1515,2363
                 */
                ids: components["parameters"]["ItemIdsQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Known buy limits, keyed by item ID. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuyLimitsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getLatestPrices: {
        parameters: {
            query: {
                /**
                 * @description Comma-separated Grand Exchange item IDs (max 500).
                 * @example 1513,1515,2363
                 */
                ids: components["parameters"]["ItemIdsQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest snapshots. Items never polled are absent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestPricesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getPriceHistory: {
        parameters: {
            query?: {
                /** @description RFC3339 start of the window. Defaults to 7 days ago. */
                from?: string;
                /** @description RFC3339 end of the window. Defaults to now. */
                to?: string;
            };
            header?: never;
            path: {
                /**
                 * @description Grand Exchange item ID.
                 * @example 1513
                 */
                itemID: components["parameters"]["ItemIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshots in ascending time order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceHistoryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getPriceChange: {
        parameters: {
            query?: {
                /**
                 * @description Lookback as a Go duration (`24h`, `168h`) or a plain number of
                 *     hours (`24`).
                 * @example 24h
                 */
                window?: components["parameters"]["Window"];
            };
            header?: never;
            path: {
                /**
                 * @description Grand Exchange item ID.
                 * @example 1513
                 */
                itemID: components["parameters"]["ItemIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The price change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceChange"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getPriceStats: {
        parameters: {
            query?: {
                /**
                 * @description Lookback as a Go duration (`24h`, `168h`) or a plain number of
                 *     hours (`24`).
                 * @example 24h
                 */
                window?: components["parameters"]["Window"];
            };
            header?: never;
            path: {
                /**
                 * @description Grand Exchange item ID.
                 * @example 1513
                 */
                itemID: components["parameters"]["ItemIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Liquidity statistics. An item with no stored history returns
             *     a zeroed block with `tier: unknown` rather than a 404.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiquidityStats"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    calculateItem: {
        parameters: {
            query?: {
                /**
                 * @description Override actions-per-hour for every step. Omit to use each
                 *     recipe's own value.
                 */
                aph?: number;
                /**
                 * @description Override the assumed round-trip buy/sell spread, as a
                 *     percentage of the guide price. Omit to use the server
                 *     default.
                 */
                spread_pct?: number;
                /**
                 * @description RS3 display name. When supplied, each path is annotated with
                 *     the skill levels it needs and whether this player has them.
                 */
                player?: string;
                /** @description Hiscore table to read. */
                mode?: components["parameters"]["HiscoreMode"];
                /**
                 * @description Include paths with an input we could not price. Their money
                 *     figures are upper bounds — the unpriced input is costed at
                 *     zero — so they are excluded by default.
                 */
                include_incomplete?: boolean;
                /**
                 * @description Comma-separated forging boosts to assume when simulating a
                 *     Smithing anvil recipe (`aph_source: ticks_forge`). Ignored by
                 *     every other recipe. Unknown tokens are rejected with a 400
                 *     rather than silently ignored. Recognised tokens: `smithing_cape`,
                 *     `careless5`, `luminite`, `rapid4`, `tinker2`, `juju`, `varrock4`,
                 *     `crystal_hammer`, `equipment20` (raises `rapid4` and `tinker2` to
                 *     their equipment-level-20 values). Omit for the conservative
                 *     floor — no perk or potion assumed.
                 * @example smithing_cape,rapid4,equipment20
                 */
                boosts?: components["parameters"]["CalcBoosts"];
            };
            header?: never;
            path: {
                /**
                 * @description Grand Exchange item ID.
                 * @example 1513
                 */
                itemID: components["parameters"]["ItemIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked production strategies. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalcResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description No recipe exists for this item, or none can be priced. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    calculateBatch: {
        parameters: {
            query: {
                /**
                 * @description Comma-separated item IDs.
                 * @example 1513,1515,2363
                 */
                ids: string;
                aph?: number;
                spread_pct?: number;
                player?: string;
                /** @description Hiscore table to read. */
                mode?: components["parameters"]["HiscoreMode"];
                include_incomplete?: boolean;
                /**
                 * @description Comma-separated forging boosts to assume when simulating a
                 *     Smithing anvil recipe (`aph_source: ticks_forge`). Ignored by
                 *     every other recipe. Unknown tokens are rejected with a 400
                 *     rather than silently ignored. Recognised tokens: `smithing_cape`,
                 *     `careless5`, `luminite`, `rapid4`, `tinker2`, `juju`, `varrock4`,
                 *     `crystal_hammer`, `equipment20` (raises `rapid4` and `tinker2` to
                 *     their equipment-level-20 values). Omit for the conservative
                 *     floor — no perk or potion assumed.
                 * @example smithing_cape,rapid4,equipment20
                 */
                boosts?: components["parameters"]["CalcBoosts"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per requested item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalcBatchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    calculateTop: {
        parameters: {
            query: {
                /** @description What to rank by. No default. */
                metric: components["schemas"]["TopMetric"];
                /**
                 * @description RS3 display name. When supplied, actions-per-hour for
                 *     Smithing recipes is derived from this player's levels where
                 *     the mechanics allow it.
                 */
                player?: string;
                /** @description Hiscore table to read. */
                mode?: components["parameters"]["HiscoreMode"];
                /** @description Restrict the ranking to recipes of this skill. */
                skill?: string;
                /**
                 * @description Rows to return. `0` or omitted uses the default of 20; a
                 *     value above 100 is clamped to 100 rather than rejected.
                 */
                limit?: number;
                /**
                 * @description Override actions-per-hour for every step of every path.
                 *     Omit to use each recipe's own value — the mechanics-derived
                 *     rates this ranking is built on.
                 */
                aph?: number;
                /**
                 * @description Override the assumed round-trip buy/sell spread, as a
                 *     percentage of the guide price. Omit to use the server
                 *     default.
                 */
                spread_pct?: number;
                /**
                 * @description Include paths with an input we could not price. Their money
                 *     figures are upper bounds, so they are excluded by default.
                 */
                include_incomplete?: boolean;
                /**
                 * @description Comma-separated forging boosts to assume when simulating a
                 *     Smithing anvil recipe (`aph_source: ticks_forge`). Ignored by
                 *     every other recipe. Unknown tokens are rejected with a 400
                 *     rather than silently ignored. Recognised tokens: `smithing_cape`,
                 *     `careless5`, `luminite`, `rapid4`, `tinker2`, `juju`, `varrock4`,
                 *     `crystal_hammer`, `equipment20` (raises `rapid4` and `tinker2` to
                 *     their equipment-level-20 values). Omit for the conservative
                 *     floor — no perk or potion assumed.
                 * @example smithing_cape,rapid4,equipment20
                 */
                boosts?: components["parameters"]["CalcBoosts"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The catalogue ranked by `metric`, best first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getPlayerHiscore: {
        parameters: {
            query?: {
                /** @description Hiscore table to read. */
                mode?: components["parameters"]["HiscoreMode"];
            };
            header?: never;
            path: {
                /** @description RS3 display name. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The player's skills. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            /** @description Player not found, or the hiscores are unreachable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Account created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredUser"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Signed token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getChatHistory: {
        parameters: {
            query?: {
                /** @description RFC3339 cursor; returns messages strictly older than this. */
                before?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Messages in chronological order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatHistoryResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    openWebSocket: {
        parameters: {
            query: {
                /** @description JWT from `/auth/login`. */
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching protocols. */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
